/** Dreamy, romantic filter for Pexels image (Image mode) – preview, carousel, and export */
export const ROMANTIC_IMAGE_FILTER =
  'brightness(0.82) contrast(0.88) saturate(0.72) sepia(0.18) hue-rotate(-8deg)';

/** Font for first-card title (TikTok-style clean sans-serif). */
export const TITLE_FONT = 'Inter, sans-serif';

/** Fallback background colors when no avgColor from image (e.g. AI cover). */
export const CARD_BG_FALLBACK_PALETTE = [
  '#1a1a2e',
  '#16213e',
  '#2d2d44',
  '#2c3e50',
  '#3d2c4a',
  '#2d3a4a',
  '#34495e',
  '#3d3d5c',
];

/** Cover image prompt IDs for automate flow. Keys are display names. */
export const COVER_IMAGE_PROMPTS = {
  boards: 'pmpt_6991006af1cc8195a60c91937fc07b7100c73c923d7ad252',
  'paper style': 'pmpt_6990f9a317588194827b173df4b3d6a30d4beef4679a5add',
  creative: 'pmpt_697bd67b55d48190ba24de5df8a84f3c0e7de9c8192b5cdc',
} as const;

export type CoverImageStyle = keyof typeof COVER_IMAGE_PROMPTS;

/** Couples-level categories only (case-insensitive). Default automate selection uses these. */
export const COUPLES_CATEGORIES = [
  'after dark',
  'deeper conversations',
  'first impressions',
  'how well do you know me',
  'spicy',
  'travelling',
];

export function getDefaultAutomateCategories(categories: string[]): string[] {
  const couplesSet = new Set(COUPLES_CATEGORIES);
  return categories.filter((c) => couplesSet.has(c.toLowerCase().trim()));
}

/** Image prompts with {x} placeholder for dynamic text. */
export const PROMPTS = [
  'A baseball cap, a bit worn out but the cap is in red, the text "{x}" embroidered on it. the text should be in white and the text should occupy only the center 70% of the screen space, leave some padding on the side. No need to show the entire cap, the text should be in the center',
  'First person view, in an empty coffee shop, you (a women) holding an iphone watching an instagram story. The story should have a red background with large white text "{x}". On the right of the phone is a cute dog looking at you.',
  'First person POV, holding a white canvas with 2 hand marks from paint, one should be sky blue and one should be pink and on the canvas, it should also have the text "{x}"',
  'Close up holding a piece of very very small torn paper, almost thumbnail size, on the paper it\'s written "{x}", it\'s like the text is typed using a type writer. Make it realistic. The text should be very clear on the piece of paper',
  'A finished puzzle, on the puzzle should have the text "{x}". Make the text cartoon style',
  'Late night home movie with a projector and the text "{x}" projected. We can only see the couple\'s back. Make the text the main focus and very clear.',
  'Picking ice cream among a bunch of flavors in the shop and on one of the flavor cards, it says "{x}". The text should be zoomed in and facing straight to you',
  'First person POV, making a heart pottery for girlfriend and on the pottery has the text "{x}" painted on it. The pottery is white and the text should be red',
  'A couple looking at a piece of art in a museum. we can only see their back and the girl\'s head is leaning slightly on the guy\'s shoulder. The art has the text "{x}" the art is very cartoony',
  'First person POV, You\'re in an arcade playing the basketball game. and on the board that shows scores, it says "{x}". There should not be any other text',
  'First person POV, in a drawing class. On the canvas, you painted a very simple image of a couple looking at the sunset, not fully colored yet, and below there\'s also this thick text: "{x}". You should be facing straight at the canvas, not at a angle. And zoom into the canvas',
  'First person POV, on the tube, youre sitting across a person reading a book, on the book cover, the title should be "{x}". zoom in on the text',
  'Cute tent at home with fairy lights. There are some lines hanging across the tent and on the lines there are characters which makes up the text "{x}". Should be very cute and realistic.',
  'First person POV, playing billiard and the text "{x}" is written with white chalk on the billiard table. Make it realistic and the text should be written on the table',
  'First person POV, You\'re at a fun and colorful arcade, on one of the arcades has the text "{x}" on one of their display',
  'First person POV, you\'re in a pottery painting class. The pottery is half painted, on it has the text "{x}" painted on it. Make it realistic. The text should be facing you straight. The text should be painted in a color where there\'s huge contrast to the pottery',
  'Girl holding a white pottery plate covering half of the face slightly smiling, on the plate it says "{x}"',
  'First person POV, In a record store with a lot of records, one of the records say "{x}" on the record cover',
  'First person POV, youre making a cake, on the top of the cake has the words "{x}" written in frosting. The cake and the frosting should have contrasting color. The text should not be cursive',
  'First person POV, you\'re in a packed theatre holding a theatre leaflet about the show, on the leaflet has the text "{x}" printed on the leaflet',
  'First person POV, you\'re ice skating with your girlfriend (can only see her arms), on the ice has the text "{x}" spray painted on the ice',
  'First person POV, Youre having a pillow fight with your girlfriend (cant see her face because shes protecting her head with the pillow), shes holding a pillow protecting herself, on the pillow has the words embroidered on it "{x}", feathers everywhere. The embroidered word should have a contrast with the pillow',
  'First person POV, you\'re on the grass in a park, painting on a white canvas. On the white canvas, it\'s a heart and then a text "{x}". You\'re facing straight at the canvas',
  'First person POV, you\'re doing a white tile drawing lesson. There are some stickers on it, there should be a text saying "{x}" painted on it with brush. The text should not be black. The tile should be facing you, the edges of the tile should be parallel to the frame',
  'First person POV, you\'re holding a cute polaroid image and on it has "{x}" written on it with marker and a heart. Focus on the text',
  'First person POV, with girlfriend on the beach (she\'s not in the picture), holding a cute polaroid, on the polaroid should be a couple and there\'s a text "{x}" written in marker with a heart',
  'First person POV, in a huge college lecture hall full of students, there\'s a professor in the center stage pointing at the lecture slides in presentation mode. Inside the slide the background should be red, it should say "{x}", make it realistic. Zoom into the slides where the text is since it should be the main focus',
  'Walking in a college town along frat row, on one of the flags it says "{x}". The flag should be red. It should be a very snowy day, the flag should occupy most of the screen space and the text should be the main focus',
  'On a highway bridge, there\'s a clean white cloth-like material poster hanging down with the text "{x}" spray painted in red, with a heart spray painted at the bottom as well. The poster should occupy the center 70% of the image and is the main focus',
  'Looking out the window on a bright day, it is very snowy with snow covering the ground. In the snow someone carved out the words "{x}" in the middle of the road with cars on both sides. The carved text should occupy about 60% width of the screen',
  'On a snowy street in New York City, there\'s a restaurant red metal sign in a heart shape, on it there\'s text "{x}" painted on it in white, it should be in the center of the image. Must be realistic',
  'Close up of the back of a car\'s windscreen covered in snow, however text carved out visibly so the carved-away part has almost no snow on it. The text says "{x}"',
  'In a bright NYC coffee shop, a female hand holding a condom wrapper with the text "{x}" on it, a very cute dog should be on the chair looking at you. Make it very realistic',
  'At home on a snowy day, pancakes on the side, there\'s a white mug in the center with a tea bag in it, you\'re holding the tea bag label which is red in color with text on it in white: "{x}". Make it realistic. Pull the teabag closer to the camera',
  'You\'re on a bus in NYC, it\'s a sunny day, on the back of the seat in front of you there\'s a sticker with black background and white text, the text says "{x}". The sticker is a bit worn off',
  'You\'re opening a fortune cookie in a restaurant and the paper is still a bit in the cookie, the message on the paper says "{x}". Make it realistic, the message should be in the center of the image. The message should be at least 60% of the screen width',
  'You\'re inside a London tube station platform, across the tracks there\'s this huge ad with the message "{x}". Must be realistic. The ad should be facing straight at you and not at an angle',
  'When you are exiting the train station on an escalator, you see a white sticker stuck on the back of one of the stairs, it says "{x}". Make it realistic',
  'First person POV, looking out the airplane window, on the window the text "{x}" is written with marker. The text should be clearly visible and not obstructed by any part of the plane outside',
  'First person POV, you\'re sitting on a plane. Looking in front of you, on the pull-out table in front of you, it has the text "{x}", the text should be clearly visible and at eye level. The text should be written with a marker',
  'First person POV, you\'re at a fun fair holding a huge cotton candy, on it has a card and on the card has the text "{x}". Make the text the focus and visible and the card should be in the cotton candy',
  'First person POV, you\'re in Ikea holding a shopping cart, on the cart is a piece of flat-pack furniture box or display panel facing the camera, on the furniture it says "{x}" in large bold lettering. The text must be the main focus: very large, centered, and easy to read; it should fill most of the frame. Bright IKEA showroom lighting, realistic',
  'First person POV, in a nice cafe holding a cup of iced matcha; on the outside of the cup the words "{x}" are printed in white as part of the cup design—not a digital overlay. Pull the cup toward the camera. Make the text the main focus, large and readable',
  'First person POV, looking down at a Valentine\'s style couples Monopoly board game; in the center of the board the text "{x}" is printed on the board. The text must be the main focus, large and clearly visible',
  'First person POV, you\'re holding your girlfriend\'s hand; on the back of her hand you\'re writing "{x}" with a black marker, with small hearts around it. Make the writing the main focus, sharp and readable',
  'First person POV, you\'re in a cinema holding a popcorn box; on the box there\'s printed text "{x}". In the background the screen should show a cute couples cartoon movie. Make the text on the box the main focus, large and clear',
  'First person POV, you look at the fridge door: a polaroid photo of a couple is held by a magnet, and on the polaroid the text "{x}" is visible. The polaroid faces straight toward the camera, not at an angle. Other cute fridge magnets around it. Make the text the main focus',
  'First person POV, you\'re making a heart-shaped pizza; the words "{x}" are spelled out in red tomato sauce on the pizza. Make the words large, readable, and the main focus',
  'First person POV, you\'re in a couples drawing class with your boyfriend: on the canvas there\'s a simple colorful doodle portrait of him (intentionally a bit rough), and he\'s good-looking in the background behind the easel. Below the drawing on the canvas, bold text says "{x}". Make that text the main focus',
  'First person POV, you\'re wearing a skirt at a tennis court looking down at the ground; a few tennis balls and a racket are visible, and on the court or pavement the text "{x}" is written on the floor. Make the text the main focus, large and readable',
  'First person POV, you\'re on a helicopter ride looking out the window; the text "{x}" is written with marker on the glass. The writing must be clear, easily visible, and the main focus',
  'First person POV, on a sunny day you\'re walking down the street; outside a coffee shop there\'s a pink ad stand with only the words "{x}" printed on it and nothing else. The stand should be the main focus, facing straight toward you',
  'A wall full of white tiles, and on one tile there is text "{x}" written with black marker. Add some heart and love themed stickers around it. Zoom in so the text is the main focus, and the tile should face the camera directly, not at an angle',
  'First person POV, you\'re at Coachella in a big crowd; far away in the crowd, a woman is holding up a large white sign with the text "{x}". Make the sign the main focus, clear and readable, and facing directly toward you',
  'First person POV, you\'re near the front stage at Coachella during daytime with a huge crowd. On the stage big screen, the text "{x}" is shown on a pink background. Zoom in so the screen text is the main focus',
  'First person POV, you\'re walking down into a crowded tube station; you look at a station sign and it says "{x}". Make the sign text clear, readable, and the main focus',
  'First person POV, you\'re standing on a crowded tube station platform and looking across the tracks at a big ad board. On the ad board, the text "{x}" is displayed. Make the text the main focus, zoom in on it, and face straight toward the ad',
  'At Coachella, a female hand is holding a condom wrapper with the text "{x}" on it. Make it very realistic and keep the text clear and readable',
  'First person POV, you\'re writing in a journal book; on the page there is text "{x}" with a heart next to it. The writing should not be cursive and should be done in single-color crayon. Make the text clear and the main focus',
  'First person POV, you\'re outdoors in the city holding a piece of pink sticky note; on it has the text "{x}" written with a thick marker. Make the text the main focus and zoom in',
  'First person POV, you\'re outdoors in the city holding a piece of pink sticky note; on it has the text "{x}" written with a thick marker. Make the text the main focus and zoom in',
  'You\'re in the coffee shop holding some light pink napkins; on the napkin has the text "{x}" written on it with marker and hearts drawn on it. Zoom in on the text and make it visible',
  'In a bright NYC coffee shop, a female hand holding a condom wrapper with the text "{x}" on it.',
] as const;

/** Funny relationship questions for games. */
export const FUNNY_QUESTIONS = [
  'If I have an identical twin sister, would you find her attractive?',
  'Am I pretty because you love me or do you love me because I\'m pretty?',
  'Would you kiss someone else for $10 million or me for $10?',
  'Would you rather never have met me or go and cheat on me right now?',
  'If I were gay would you still love me?',
  'If I broke up with you, would you move on?',
  'Date me and never have your favorite food again or still be able to have your fav food but I\'m gone?',
  'If I got into a fight with your mom, whose side would you pick?',
  'Would you rather have me cheat on you or would you cheat on me?',
  'Would you forgive me for cheating once if it saved your life?',
  'Would you help me cover up a body without asking any questions?',
  'Would you let another guy kiss me if it saves your life?',
  'Would you rob the bank to pay for my hospital bills?',
  'If you have 60 seconds to make me cry for $1 mil, what would you do?',
  'If you\'re already in a relationship, would you leave them for me?',
  'Would you still stay with me if I get a year older every day?',
  'Would you still stay with me if I gain a pound of weight every day?',
  'If I were born a man with the same personality, would you still love me?',
  'Would you still date me if Im ugly but loyal or the prettiest girl in the world but a cheater?',
  'If I gain 50 pounds, would you still find me attractive?',
  'If me and you ex switch bodies, who would you be in love with?',
  'Would you stay with me if I loose both my arms and legs?',
  'Would you rather kiss another person or die in a plane crash?',
  'If I died and you remarry, what would the other person have that I don\'t?',
  'Would you rather lose your laptop and phone forever or lose me for a week?',
  'If you had to choose between never using the internet again or never seeing me again, which one are you picking?',
  'Would you let me start an OF if it gives us generational wealth?',
  'If I became a prostitute, would you still love me?',
  'Would you rather be the jealous one or the one causing jealousy?',
  'Would you rather get my name tattooed on your neck or free or ex\'s for $1 mil?',
  'Would you rather have an open relationship for a month or no intimacy for 1 year?',
  'Would you rather see me get with another person once or no intimacy for a year?',
  'If one of us has to cheat, who would it be?',
  'Would you rather forget everything about our past or never be able to imagine a future with me?',
  'Would you spend a year without me for $1 mil?',
  'If we break up, who would hook up first?',
  'If my little sister and I are stuck in a burning building, who would you save first?',
  'If you\'re in a room with ever person you\'ve ever been interested in, what\'s your first move?',
  'If someone offered you $1 mil to punch me in the face as hard as you can, would you do it?',
  'How long would I have to be in a coma for, before you to start dating other people?',
  'How long would I have to be in a coma for before you start using dating apps again?',
  'Would you rather see another men n*ked or another women n*ked?',
  'If you need to kiss either your best friend or your ex to save my life, who would it be?',
  'If you found a soulmate, would you leave me for them?',
  'If I have to spend a night at one of your friend\'s place, who\'s would you not let me spend it at?',
  'Would you rather I kiss your best friend once or stay loyal but never have sex with you again?',
  'Would you rather wake up tomorrow with zero memory of me or know everything about me but be forced to break up right now?',
  'Would you rather I become "too hot" or stay average?',
  'If I cheated once but confessed immediately, would you forgive me?',
  'Would you rather accidentally sent a naughty pic to my mom or dad?',
  'What would you do if one of your friends ask me to go to a party with them, just me and them?',
  'Marry me right now or wait 10 years to be sure?',
  'Spend a night with your ex or lose $50,000?',
  'Would you rather see me flirt with someone or see someone flirt with me?',
  'When am I better looking, now or when we first met?',
  'If you have to pick between me or unlimited shopping forever, what would you pick?',
  'Would you rather know my biggest turn on or my biggest turn off?',
  'Would you rather drop all your friends or the relationship?',
  'Is it cheating if I\'m still friends with a person I used to like?',
  'Would you still love me if I have a body count of over 100?',
  'Is it cheating if I sleep in the same bed with an opposite sex friend but they\'re gay?',
  'Would you rather never kiss me again or argue with me everyday?',
  'Would you rather cheat on me or never be able to see me again?',
  'Would you rather have 100 kids or no kids at all?',
  'Would you kiss my best friend to save my life?',
  'Would you still love me if my lower body is paralyzed?',
  'Would you rather forget me for a day or let me read all your DMs?',
  'Would you rather walk in on your parents or have them walk in on us?',
  'Would you rather hook up with you ex or have my ex hook up with me?',
  'Would you rather get $1 mil but I can\'t celebrate your birthday with you or spend your birthday with me?',
  'Who do you love more, your mom or me?',
  'Would you rather I text my ex once or you stop using TikTok?',
  'If my ex offered me $50,000 to meet them for dinner, would you let me go?',
  'Would you rather I have a wild past or a boring one?',
  'Is our relationship good or you\'ve just never had any better?',
  'Which one fits me best, intelligent but ugly or beautiful but dumb?',
  'Would you rather give up video games for a year or give up complaining for a year?',
  'Who from my friend group do you think is secretly into you?',
  'Would you rather have 10 million dollars right now, but never see me again, or stay with me and be broke?',
  'If you had a one-time-use time machine to alter one thing about our relationship, what are you changing?',
  'Would you rather go back in time so you could know me longer, or spend more time with me now?',
  'Would you rather hold my hand for four hours straight every day or never hold it again?',
  'Would you rather TikTok Live all our arguments, or never use the Internet again?',
  'If we are in Beauty and the Beast, who\'s the beauty and who\'s the beast?',
  'Would you rather be paralyzed from the neck down or hug another woman?',
  'Would you rather kiss another woman or fight a grizzly bear?',
  'Be honest, who\'s more weird?',
  'Would you rather lose all our messages or photos together?',
  'If you lost me in a supermarket, where would you look for me first?',
  'Do you think you can do better than me?',
  'Who wears the pants in the relationship?',
  'Do you actually listen to me when I speak or do you just wait until your turn?',
  'Would you rather I get horny only once a month or want it every day?',
] as const;

/** Flirty relationship questions for games. */
export const FLIRTY_QUESTIONS = [
  'What would you do if I kissed you right now?',
  'What\'s your favorite part of my body?',
  'What\'s the most attractive thing I do without realizing?',
  'If we were alone right now, what would you want to do?',
  'What\'s something you want to try with me that we haven\'t yet?',
  'What\'s your favorite memory of us being close?',
  'Do you like it when I take the lead or when you do?',
  'What\'s one compliment you want from me more often?',
  'What\'s your favorite kind of kiss from me?',
  'What\'s something small I do that turns you on?',
] as const;

/** "Me or you" questions for couples games. */
export const ME_OR_YOU_QUESTIONS = [
  'Who’s more in love right now?',
  'Who thinks more about the other person?',
  'Who would struggle more if this ended?',
  'Who’s settling and who’s reaching in this relationship?',
  'Who gets hit on more often?',
  'Who’s more likely to sleep in and miss an exam?',
  'Who would more likely be late and miss a flight?',
  'Who has a wilder past?',
  'Who would be a better parent?',
  'Who’s funnier?',
  'Who is more athletic?',
  'Who is more likely to become successful?',
  'Who is smarter?',
  'Who is more popular?',
  'Who is more tempted by lust?',
  'Who is more confident?',
  'Who is more toxic?',
  'Who is more likely to start a fight?',
  'Who makes no sense?',
  'Who is always right?',
  'Who has more friends?',
  'Who has a better body?',
  'Who is more likely to become sugar daddy / mama?',
  'Who is more likely to cheat?',
  'Who is more likely to lie?',
  'Who is more immature?',
  'Who is more fashionable?',
  'Who has better sense of humor?',
  'Who is better at flirting?',
  'Who is more likely to survive in deserted island?',
  'Who is more likely to win a fight against a kangaroo?',
  'Who is more likely to be famous?',
  'Who is more likely to be on the Forbes list?',
  'Who is more likely to have a one night stand?',
  'Who is more likely to have an onlyfans?',
] as const;
